# Update a controller's task values with the manager

# Name of the action on the controller that is updating its task
string controller_action_name

# New point value for the controller's task
float32 new_task_point_value

# New time to complete for the controller's task
float32 new_task_time_to_complete

# New likelihood of success for the controller's task
float32 new_task_likelihood_of_success
---
##
## Status Codes:
##
uint8 OK=0
uint8 RETRY=1
uint8 FATAL=2
uint8 UNKNOWN=3

# Status of the update task request
uint8 request_status