<?xml version="1.0"?>
<package format="3">
  <name>navigator</name>
  <version>1.0.0</version>
  <description>Navigation for OAK-D Arena</description>
  <maintainer email="user@todo.com">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>nav2_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>libpcl-all-dev</depend>
  <depend>depthai_ros_driver</depend>
  <depend>slam_toolbox</depend>
  <depend>tf2_ros</depend>

  <export><build_type>ament_cmake</build_type></export>
</package>