name: ROS2 Colcon Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy

    steps:
      - uses: actions/checkout@v4

      - name: Install CI tools
        run: |
          apt update
          apt install -y \
            build-essential \
            python3-rosdep \
            python3-colcon-common-extensions
            python3-ament-package

          rosdep init || true
          rosdep update

      - name: Build workspace
        shell: bash
        run: |
          set -e
          source /opt/ros/jazzy/setup.bash

          rosdep install -i --from-path src --rosdistro jazzy -y
          colcon build